version: "3.8"

services:
  php:
    build: ./php
    container_name: ex-php
    volumes:
      - ./php:/var/www/html

  nginx:
    image: nginx:latest
    container_name: ex-nginx
    volumes:
      - ./nginx/nginx.conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/var/www/html
    ports:
      - "80:80"
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
    depends_on:
      - php
